typography_spectrum: 0.7547956285998225
color:
  brandStrength: 0.13690294092521071
  lightness: 0.548111051088199
  saturation: 0.4783033945132047
  rhythmicContrast: 0.9358962767291814
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.9105294388718903
author:
  name: Ben Kolb
  email: benk04@vt.edu
  url: Equitrex.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/80ba251f-df1b-4ca8-ac5b-f6edf9bfdd6b.png
name: Equitrex
title: Balance. Progress. Purpose.
description: Spread purpose by sharing it.
